# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-08 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181007_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='avatar',
            new_name='ava',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
